### PR TITLE
Popup Support

### PR DESCRIPTION
**Pull request by JPEWdev**
Adds library support for the UIProcess to show popup windows.

### CODE REVIEW

**Comment by aperezdc** [comment]
I think that nowadays the preferref way to go about this would be connecting to the `WebKitWebView::show-option-menu` and handle showing the popup in the application that is embedding a WPE web view. That way it is not needed to add additional API in WPEBackend. The same approach would be valid for context menus (using the `WebKitWebView::context-menu` signal) and others like showing file choosers.

@zdobersek Any thoughts on this?

**Comment by aperezdc** [comment]
@JPEWdev Is this PR still relevant, or does the suggested alternative of using the signals in the new GLib-based API work for you?

**Comment by JPEWdev** [comment]
I haven't had a chance to loop back around and look, but this has been open so long it probably isn't useful to keep it open anymore.

**Comment by aperezdc** [comment]
@JPEWdev If you get to revisit this in the future, and the PR is still valuable, feel free to reopen it. Thanks for commenting!

**Pull request closed without merging**
