### PR TITLE
Popup menus

### PR DESCRIPTION
**Pull request by JPEWdev**
Adds support for WebKit to allocate popup menus.

### CODE REVIEW

**Review by aperezdc — COMMENTED** [review]
What is the advantage of doing this, and funneling things through libwpe? 

The `WebKitWebView:show-option-menu` can be used directly by an embedding application to implement popups in any way it may need already. For example this is done in https://github.com/Igalia/cog/pull/190 using Cairo to paint the menus—but it could have used anything else.

Unless there is some use case that this solves and cannot be taken care of handling the `show-option-menu` signal, I would rather not merge this :thinking:

**Comment by JPEWdev** [comment]
I think this is necessary and I just forgot to close it. Thanks :)

**Review by mcatanzaro — CHANGES_REQUESTED** [review]
Apparently I have a pending review on this PR from over a year ago that I hadn't submitted, oops. :P Anyway, just a warning there are ABI issues here:

**Comment by mcatanzaro** [comment]
Not that it matters anymore. :)

**Pull request closed without merging**
